version: "3.4"

services:

  flghtStatus-service:
    container_name: flightStatus-service
    build: ./flightStatus-service
    image: 266045683658.dkr.ecr.us-east-1.amazonaws.com/flightStatus-service:latest
    depends_on:
      - config-service
    entrypoint: sh
    command: >
      -c "
      while ! (nc -z config-service.carbee 8088); do sleep 5; echo 'Waiting for config-server to start-up...'; done;
      java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=staging /app.jar
      "
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 128m